// console.log(10 + 10);     
// console.log(10 + "10"); 
// console.log(10 + +"10");  
// console.log(10+"10"+10);  
// console.log(10+ +"10" + 10);
// console.log(10 - "2");
// console.log(10 - "2" - "8");
// console.log(10+"2" - "2");
// console.log(10>9>8);
// console.log(10 * "10");
// console.log(100 / "100");
// console.log(100/"0");
// console.log(100 + +"100" - "100" * "100");
// console.log(1 == "1");
console.log(1 === "1");
console.log(1 == "one");
console.log(1 === "one");
// console.log(1+true);
// console.log(1 - true);
// console.log(1 + true - false);
// console.log("1" + true);
// console.log(+"1" + true);
// console.log(undefined == undefined);
// console.log(undefined === undefined);
// console.log(null == null);
// console.log(null === null);
// console.log(undefined == null);
// console.log(undefined === null);
// console.log(2+NaN);
// console.log("2"+NaN);
// console.log("2"+undefined);
// console.log(2+undefined);
// console.log(typeof "123");
// console.log(typeof 2);
// console.log(typeof true);
// console.log(typeof undefined);
// console.log(typeof null);
// console.log(typeof []);
// console.log(typeof 1n);
// console.log(typeof 1n+2n);
// console.log(typeof 1+2n);
// console.log(typeof 1/1n);